resources:
- name: test-unit
  type: git
  source:
    - uri: {{github-project}}
      branch: concourse-in-progress
      private_key: {{github-private-key}}



jobs:
- name: recipe-test
  plan:
    - get: test-unit
      trigger: true
    - task: build-test
      params:
        PROJECT: {{project}}
      file: concourse-docker-repo/build-test.yml

